/*
 * Copyright (c) 2026 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work
 * except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the Licence for the specific language
 * governing permissions and limitations under the Licence.
 */

package eu.europa.ec.dashboardfeature.ui.component

import androidx.compose.ui.graphics.Color
import eu.europa.ec.corelogic.model.DocumentIdentifier
import kotlin.math.abs

/**
 * Fixed pastel background palette for credential cards, Lissi-style. Each distinct
 * [DocumentIdentifier.formatType] is deterministically hashed to one of these colors, so a
 * given credential *type* (e.g. "PID (MSO MDoc)" vs "PID (SD-JWT VC Compact)") always gets the
 * same color, and different types are very likely to get different colors, without hard-coding
 * a color per known type.
 *
 * Shared between the documents list ([eu.europa.ec.dashboardfeature.ui.documents.list.DocumentsScreen])
 * and the document details screen ([eu.europa.ec.dashboardfeature.ui.documents.detail.DocumentDetailsScreen])
 * so the same credential keeps the same color everywhere it is shown.
 */
private val CREDENTIAL_PASTEL_PALETTE: List<Color> = listOf(
    Color(0xFFC3D4FA), // blue
    Color(0xFFD6C8F5), // violet
    Color(0xFFC3E8CE), // green
    Color(0xFFF8D9AE), // amber
    Color(0xFFF5C7DA), // pink
    Color(0xFFC3EDED), // cyan
)

fun DocumentIdentifier.toCredentialPastelColor(): Color {
    val index = Math.floorMod(formatType.hashCode(), CREDENTIAL_PASTEL_PALETTE.size)
    return CREDENTIAL_PASTEL_PALETTE[index]
}

private fun hslToColor(hueDegrees: Float, saturation: Float, lightness: Float): Color {
    val c = (1f - abs(2f * lightness - 1f)) * saturation
    val hPrime = (hueDegrees % 360f) / 60f
    val x = c * (1f - abs(hPrime % 2f - 1f))
    val m = lightness - c / 2f
    val (r, g, b) = when {
        hPrime < 1f -> Triple(c, x, 0f)
        hPrime < 2f -> Triple(x, c, 0f)
        hPrime < 3f -> Triple(0f, c, x)
        hPrime < 4f -> Triple(0f, x, c)
        hPrime < 5f -> Triple(x, 0f, c)
        else -> Triple(c, 0f, x)
    }
    return Color(red = r + m, green = g + m, blue = b + m)
}

/** Saturation/lightness "recipe" every generated pair below shares, matching the 3 curated ones. */
private const val METALLIC_SATURATION = 0.55f
private const val METALLIC_LIGHT_LIGHTNESS = 0.42f
private const val METALLIC_DARK_LIGHTNESS = 0.14f

/**
 * Hue step between consecutive generated colors. The golden angle (~137.5°) is the standard trick
 * for handing out N colors one at a time so that any two *consecutive* ones always land far apart
 * on the hue wheel — i.e. no two neighboring credentials ever read as "the same family" — while
 * still cycling through the full hue range as more are generated.
 */
private const val GOLDEN_ANGLE_DEGREES = 137.508f
private const val CREDENTIAL_PALETTE_SIZE = 50

/**
 * Metallic gradient palette for the large credential cards, indexed by a document's position among
 * ALL the user's documents (see [rankedByCategory] / [toCredentialMetallicGradient]): each pair is
 * a (lighter, darker) shade of the same hue, for a diagonal light-to-dark background.
 *
 * Index 0/1/2 (indigo/teal/wine) are colors sampled directly off the reference wallet screenshot
 * `colores.png`, per explicit request — the 1st, 2nd and 3rd credential always get these exact
 * three regardless of type. Indices 3-49 are generated by stepping the hue wheel by the golden
 * angle each time (see [GOLDEN_ANGLE_DEGREES]), so the 4th credential onward each gets a distinct,
 * non-repeating color, and consecutive credentials never look like close variants of each other.
 */
private val CREDENTIAL_METALLIC_PALETTE: List<Pair<Color, Color>> = buildList {
    add(Color(0xFF4A4FC5) to Color(0xFF17173F)) // 0: indigo — colores.png "Email" card
    add(Color(0xFF1D8A76) to Color(0xFF0A2620)) // 1: teal — colores.png "Verifiable ID" card
    add(Color(0xFF8C2142) to Color(0xFF3A0F1D)) // 2: wine — colores.png "Self-Attested" card

    // Start comfortably away from wine's own hue (~345°) so index 3 doesn't read as "more wine".
    var hue = 60f
    repeat(CREDENTIAL_PALETTE_SIZE - size) {
        add(
            hslToColor(hue, METALLIC_SATURATION, METALLIC_LIGHT_LIGHTNESS) to
                hslToColor(hue, METALLIC_SATURATION, METALLIC_DARK_LIGHTNESS)
        )
        hue = (hue + GOLDEN_ANGLE_DEGREES) % 360f
    }
}

/**
 * The 1st and 2nd credential (this wallet's two PID variants) always get the exact indigo/teal
 * reference colors; every other document is colored purely by [positionIndex] — its rank among
 * ALL the user's documents, category-first (see [rankedByCategory]) — cycling through the palette
 * once every [CREDENTIAL_PALETTE_SIZE] documents.
 */
fun DocumentIdentifier.toCredentialMetallicGradient(positionIndex: Int): Pair<Color, Color> {
    return when (this) {
        is DocumentIdentifier.MdocPid -> CREDENTIAL_METALLIC_PALETTE[0]
        is DocumentIdentifier.SdJwtPid -> CREDENTIAL_METALLIC_PALETTE[1]
        else -> CREDENTIAL_METALLIC_PALETTE[positionIndex.mod(CREDENTIAL_PALETTE_SIZE)]
    }
}
